### ISSUE TITLE
code problem

### ISSUE THREAD

**Issue by suixin1424** [zllxot/CORE#4]
![e2f27f1c25f6779591f69903924ee19](https://github.com/zllxot/CORE/assets/22639359/a3bb9cb3-cabb-4edb-aa55-ccecc1d1e400)  
where is the opencood.models.voxel.net.core

**Comment by feeling0414-lab** [comment]
I meet the same problem.

**Comment by zllxot** [comment]
Thank you for your attention and inquiry. I have updated the code.
